### ISSUE TITLE
Would you mind if I use your homepage as a template by adding your license or so?

### ISSUE THREAD

**Issue by lesleychou** [Romero027/Romero027.github.io#1]
Hi Xiangfeng,

I'm Yajie and I'm also doing video related research.
I really like your homepage style! I'm wondering if I could use your homepage as a template for myself? 
I can add your license or so if you would agree, if you don’t like it then I would not do it!

Also, thanks for the paper summaries on your blog! It's quite nice overviews :)

**Comment by Romero027** [comment]
@lesleychou 

eh, I'm sorry that I somehow overlooked your message.

Thanks for your kind words and feel free to use it! I'm glad you find the summaries useful :)
